### ISSUE TITLE
_disassociateFromOldInverses hasMany -> belongsTo -> hasMany doesnt remove relationship

### ISSUE THREAD

**Issue by ghost** [miragejs/ember-cli-mirage#1375]
lets say i have following models: Product and Tool

```
// Product Model

import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string'),

  tools: DS.hasMany('tool'),
});
```

```
// Tool Model

import DS from 'ember-data';

export default DS.Model.extend({
  product: DS.belongsTo('product'),
});

```

i have two products and every product has 2 Tools in its hasMany relationship.

```
id 1: Product 1
  id 1: Tool 1.1
  id 2: Tool 1.2
id 2: Product 2
  id 3: Tool 2.1
  id 4: Tool 2.2
```

now when i save product 1 whit following toolIds: [1, 2, 3] Tool 2.1 with id 3 get re-associated with Product 1, thats fine. But in the mirage db Product 2 hasMany association it still associates to Tool 2.1 with id 3.

if i do it the other side lets say i update Tool 2.1 with id 3 with following productId: 1 everything is fine and it gets removed from Product 2.

as a workaround i use 
```
this.patch('products/:id', function ({ products, tools }, request) {
    const attrs = this.normalizedRequestAttrs();
    const { id } = request.params;
    const product = products.find(id);

    tools.find(attrs.toolIds).update({ product: product });

    return product.update(attrs);
  });
```

for update and
```
this.post('products', function ({ products, tools }) {
    const attrs = this.normalizedRequestAttrs();
    const toolIds = attrs.toolIds;

    delete attrs.toolIds

    const product = products.create(attrs);

    tools.find(toolIds).update({ product: product });

    return product
  });
```
for create.

is this is this behavior expected? Or doesn't Mirage respect relationships with more then 2 edges in view of one-way relationships?

**Comment by samselikoff** [comment]
😬 sorry for apparently never responding here!

In this case I would have expected Mirage to maintain the keys and for the tool to be disassociated from the old product. That's because given your schema, Mirage will treat the two relationships as inverses of each and therefore keep them in sync.

We do have test coverage around this area but it's totally possible we're missing some case. However I'm going to close now as it's stale, but if you (or anyone) runs into something similar please add a comment and we can investigate!
