### ISSUE TITLE
Is API calls required to load factories? 

### ISSUE THREAD

**Issue by Subaku** [miragejs/ember-cli-mirage#1837]
I'm noticing that without an explicit API call my factories don't seed the database. Is this by design? Trying to understand the docs and it doesn't seem to point this out clearly. 

To clarify I've got two factories and in one I set some relationships by calling `server.create(...)` in the afterCreate hook. The Ember Inspector shows zero entities for Ember Data unless I explicitly do something like `this.store.findAll('place');`. Was under the impression that simply calling `server.create` or `server.createList` is enough to seed data?

Thanks for clarifying.

**Comment by samselikoff** [comment]
Hm, seems strange. Are you in dev? Do you have any fixtures defined?

There's some weird legacy behavior on when/how seeds are loaded...

**Comment by Subaku** [comment]
I should be in dev. I'm just running `ember serve` and I do not have any fixtures defined. Let me know of anything I can check on for you.

**Comment by samselikoff** [comment]
Simplified reproduction as a repo I can check out is usually the fastest way!

**Comment by Subaku** [comment]
Here you go boss.

https://github.com/Subaku/ember-mirage-issue.git

Check inside the index route. You'll find the issue in there. Appreciate it!

**Comment by samselikoff** [comment]
Ok so, the reason this is happening is because your _ember_ app hasn't loaded the data. However, they are loaded into Mirage's db.

This is slightly confusing when you start out but, Mirage's database + models + factories have nothing to do with Ember data. Mirage is an abstraction around your _server_, so you should think of it like your backend.

If you open up `mirage/config.js` and add this to your file

```js
this.get('/asset'); // your code
window.server = this; // add this
```

then comment out that line in the route

```js
// assetLocations: this.store.findAll('asset-location'), comment this out
```

then your UI will be empty – but if you open the console, type in `server.db.dump()` and you'll see all your data is there in Mirage.

The idea is, the data is in Mirage (your backend), waiting for your Ember app (your frontend) to query. So that's why it's not going to be in either the UI or in Ember's inspector until your Ember app queries for it!

Make sense?

**Comment by Subaku** [comment]
Ah! I kinda had this in the back of my mind but wasn't 100% sure. Make complete sense. Thanks a lot!
