### ISSUE TITLE
Discrepancy side loading nested relationships between JSONAPISerializer and RestSerializer

### ISSUE THREAD

**Issue by spicalous** [miragejs/ember-cli-mirage#1926]
Hi all,

FYI (https://github.com/miragejs/ember-cli-mirage-boilerplate) is now 404'ing

# Question
There seems to be some discrepancy between `JSONAPISerializer` and `RestSerializer` and side loading nested relationships

I have described the situation below, and also have a repo here demonstrating my problem: https://github.com/spicalous/mirage-serializer-example

Given some models:
```
// app/models/menu-item.js
export default class MenuItemModel extends Model {
  @attr('string') name;
  @attr('number') price;
  @hasMany('order-item') orderItems;
}

// app/models/order-item.js
export default class OrderItemModel extends Model {
  @attr('number') quantity;
  @belongsTo('menu-item') menuItem
}

// app/models/order.js
export default class OrderModel extends Model {
  @hasMany('order-item') orderItems;
}
```
And we request all order records with side loading
```
// app/routes/application.js
export default class ApplicationRoute extends Route {
  model() {
    return this.store.findAll('order', { include: 'orderItems,orderItems.menuItem' });
  }
}
```
When using `JSONAPISerializer`, everything works as expected
 - mirage responds with an `includes` property in the response with all the `order-item` and `menu-item` records.

However when using `RestSerializer`, nothing is side loaded at all. If I customise the mirage `order` `RestSerializer` like so:
```
import AppSerializer from './application'; // AppSerializer extends RestSerializer

export default AppSerializer.extend({
  include: ['orderItems', 'orderItems.menuItem']
});
```
But it will only side load `order-item` records and not `menu-item` records.

I know that `includes` belongs to JSON api specification. It seems to only be half working when using RestSerializer? Is this expected?

Thanks for your time! Happy to help out where possible!

**Comment by samselikoff** [comment]
Yep you got it, query params include works with JSONAPISerializer out of the box because it's part of the spec. (All Serializer's `include` hooks can be a function though, and that function takes in a request. So you can kind of reimplement some of that functionality with RestSerializer. [Here are the docs](https://miragejs.com/api/classes/serializer/#include).)

The problem in your case is that dot-paths don't work in the `include` hook. The way serializer includes work is by looking at each model-specific serializer. So in this case, if you want to include an order's orderItems, and each orderItem's menuItem, you'd need two serializers like this:

```js
import { Server, Model, belongsTo, hasMany, RestSerializer } from "miragejs"

export default new Server({
  models: {
    menuItem: Model.extend({
      orderItems: hasMany()
    }),

    orderItem: Model.extend({
      menuItem: belongsTo()
    }),

    order: Model.extend({
      orderItems: hasMany()
    })
  },

  serializers: {
    application: RestSerializer,
    order: RestSerializer.extend({
      include: ['orderItems']
    }),
    orderItem: RestSerializer.extend({
      include: ['menuItem']
    })
  },

  seeds(server) {
    let menuItem = server.create('menu-item')
    let orderItems = server.createList('order-item', 3, { menuItem })
    let order = server.create('order', { orderItems })
  },

  routes() {
    this.resource("order")
  },
})
```

Try copying + pasting the above [into our WIP Inspector](https://deploy-preview-477--miragejs.netlify.com/inspector/), then putting `orders` in the Request input and seeing the response. You should see all your data!

**Comment by samselikoff** [comment]
And thanks for reporting about the boilerplate link I fixed it :) 

We're hoping the inspector will replace the need for it!

**Comment by spicalous** [comment]
Thanks Sam! This has resolved the issue for me :)
