### ISSUE TITLE
Question - Dependabot: why not ignore more Ember dependencies than ember-cli ?

### ISSUE THREAD

**Issue by MrChocolatine** [miragejs/ember-cli-mirage#1931]
It is neither an issue nor a request for a feature, but simply a question regarding your @dependabot [configuration file](https://github.com/miragejs/ember-cli-mirage/blob/master/.dependabot/config.yml).

I already watched [the video EmberMap](https://embermap.com/video/automate-your-dependency-upgrades-with-dependabot) for Dependabot.

Why only ignoring `ember-cli` upgrades and not `ember-data` and/or `ember-source` too, for instance ? Or any other "direct Ember dependency" ?
I would like to better understand.

Thank you for your feedback.

**Comment by samselikoff** [comment]
We do that because the upgrade process for `ember-cli` often involves changes to an app's or addon's generated files. You usually do this with `ember-cli-update`, which tries to automate the file changes across Ember CLI versions.

I suppose we could tell Dependabot to bump Ember CLI but hold off on merging, then we could check out the branch, run `ember-cli-update` and go from there. But we just usually do it on our own since it involves this step.

`ember-data` and `ember-source` don't have this issue, their changes are similar to other libraries and only affect their own APIs rather than the file structure on disk.

Happy to answer any more questions!

**Comment by MrChocolatine** [comment]
> We do that because the upgrade process for `ember-cli` often involves changes to an app's or addon's generated files. You usually do this with `ember-cli-update`, which tries to automate the file changes across Ember CLI versions.
> 
> I suppose we could tell Dependabot to bump Ember CLI but hold off on merging, then we could check out the branch, run `ember-cli-update` and go from there. But we just usually do it on our own since it involves this step.

Yes of course, I totally agree with that.

> `ember-data` and `ember-source` don't have this issue, their changes are similar to other libraries and only affect their own APIs rather than the file structure on disk.

That's what I was wondering.

Thank you very much ;-) !
