### ISSUE TITLE
can't import the test helper addon in mirage

### ISSUE THREAD

**Issue by mockey-jockey** [miragejs/ember-cli-mirage#1999]
# question

Facing the same issue - https://github.com/miragejs/ember-cli-mirage/issues/1445

Uncaught Error: Could not find module `project-name/tests/helpers/push-mirage-into-store` imported from `project-name/mirage/factories/addon
`

Initially got this error and tried @makepanic instructions

After that

Uncaught Error: Could not find module `@ember/test-helpers `imported from `project-name/mirage/helpers/push-mirage-into-store`

can you pls help here to resolve this.

**Comment by cah-briangantzler** [comment]
LOL, I had followed the link and ended up posting the reply in the closed issue.    Reposting here


I am curious why you would be using pushMirageToStore from a factory, given that its job is to create a record in the mirage store.

The main problem here is that this method needs to lookup both the store and the mirage server to push from one to the other. It does this by getting the context of the test and then using that to lookup the store and the server. This context is what is being imported from the test-helpers and only available with ember tests.

import { getContext } from '@ember/test-helpers';

  let context = getContext();
  let store = context.owner.lookup('service:store');

  let resources = Object.keys(context.server.schema) ..... // server is derived from context
if you want to use pushMirageToStore outside of tests, you need to make a new version that you can pass the store and the server into that you can access. If you do not have access to the store and server, then that would be the next problem to tackle.

As a note. I have a modified version of the pushToStore that allows for you to pass a config so that you can specify which tables to push as well as provide a where.

I quickly modified this to accept a store and server although did not fully test, but perhaps this would help. As noted, you cant put this in test/helpers or addon-test-helpers because again, only accessible from tests

NOTE: This was meant to be deployed within ec-mirage as a PR. You will have to remove the asserts because of where they are imported from and the params are backwards from ember assert so you cant just replace the import with the one from ember debug. Looks like some of the comments in the description need adjusted to take into account the new server and store arguments.

Wanted to get this to you quickly, but if willing to wait a bit, wil do more work on it.

import { run } from '@ember/runloop';
import assert from '../addon/assert';

let pushMirageRecordsIntoStore = function(store, server, resource, where) {
  let models = server.schema[resource].all();
  let modelName = models.modelName;
  if (typeof where === "object") {
    models = server.schema[resource].where(where);
  }

  if (models.length > 0) {
    let serializer = server.serializerOrRegistry.serializerFor(modelName);

    let originalAlwaysIncludeLinkageData = serializer.alwaysIncludeLinkageData;
    serializer.alwaysIncludeLinkageData = true;

    let json = serializer.serialize(models);

    serializer.alwaysIncludeLinkageData = originalAlwaysIncludeLinkageData;
    run(() => {
      let jsonObj = {};
      jsonObj[`${modelName}`] = json;
      store.pushPayload(jsonObj);
    });
  }

  return models;
}

/**
 * This utility pushes the mirage store into the ember store
 *
 * You may also call this utility with an array of resource names. ['accounts', 'accountTypes']. These must
 * be the resource names camelized.
 *
 * You may also call it with a hash. This hash will have the resource names as the keys and the values will either
 * be true (push all models for that resource) or a where hash that will be applied to the that resource.
 * {
 *   accounts: true,
 *   accountTypes: { state: 'OH' }
 * }
 *
 * @param server   The mirage server
 * @param store    the store you wish mirage to push to
 * @param config   undefined means push all resources
 *                 An array will push only the resources in the array
 *                 hash in the form of resource=value    Value may be true, all models, or a where hash
 */
let pushMirageIntoStore = function(server, store, config) {
  assert(store, "You must supply a store to pushMirageIntoStore");
  assert(server, "You must supply a mirage server to pushMirageIntoStore");

  let resources = Object.keys(server.schema)
    .filter(key => server.schema[key].all !== undefined); // Get the resources

  let where = {};

  if (config) {
    let includes;
    if (Array.isArray(config)) {
      includes = config;
    } else {
      includes = Object.keys(config);
      where = config;
    }

    resources = includes.filter(item => {
      let found = resources.includes(item);
      assert(found, `Model of type '${item}' does not exist for push mirage into store.`);
      return found;
    });
  }

  resources.forEach(resource => {
    pushMirageRecordsIntoStore(store, server, resource, where[resource]);
  });
}

export {
  pushMirageIntoStore,
  pushMirageRecordsIntoStore
}
I was going to make the non server/store version in a PR, but given the problems, perhaps I should also provide this one as well.

**Comment by mockey-jockey** [comment]
Hey, @cah-briangantzler thanks a lot for your time and detailed solution.

I think it's working now and my bad ended with some other issue.

I will check and revert back to you.

**Comment by mockey-jockey** [comment]
Now am getting this issue:
Uncaught Error: Could not find module `different-project-name/models/bot-cortex` imported from `project-name/models/bot-cortex`

Earlier it was a problem with inside the same repo. Now it's pointing different repo, in my project we are connecting from different repo...that's kind of edge case.

@cah-briangantzler Can you pls here and give some idea about this.

**Comment by cah-briangantzler** [comment]
based on the  paths, are those Ember Data Models? is one and addon the is being consumed by the other?

Based on paths alone I  dont think there is enough info to determine the problem

**Comment by mockey-jockey** [comment]
Yes, you're correct,  it is data models only and its consumed the addon by the other.pls, let me know if u need more info.

**Comment by cah-briangantzler** [comment]
This appears to be no longer a mirage question but just an ember question.

In the addon, your model is defined in the addon directory, but do you have a file in the app directory that contains an export of the model? something like this
```js
export { default } from 'different-project-name/models/bot-cortex';
```

Why are you importing an ember data model, are you attempting to extend it? If you are just trying to use a model in your app that is defined in an addon, you do not need to import it, having the correct file in app directory of the addon is enough.

**Comment by mockey-jockey** [comment]
hey, thanks a lot  @cah-briangantzler for keep clearing my obstacles.

` "***-engine": "git+ssh://git@github.com/****/****-engine.git#v4.4.2"` like this adding in `package.json` as `dependencies`

we don't have any file regarding that in the app directory

**Comment by cah-briangantzler** [comment]
It depends on how and why you are importing if that file is required or not.

It sounds like the addon just needed to be added as a dependency. Glas you found you answer

**Comment by mockey-jockey** [comment]
No, I didn't get this. 

Yes it's a mandatory addon from our end we need to import it. So what's next step to proceed this @cah-briangantzler

**Comment by cah-briangantzler** [comment]
Im not sure without seeing a lot more code.  I havent used engines, but from all I know they shouldnt be any different than a regular addon.

You have a model defined in the engine,  in the addon/models/bot-cortex that looks like below, the export default is important
```js 
export default Model.extend({
...
});
```

The in the application in app/models/bot-cortex you have the following (replacing engine with the name of your repo). This is assuming you are extending the model defined in the engine. Note that the import for Model is from the engine, not Ember Data
```js
import Model from 'engine/models/bot-cortext';

export default Model({
});
```
If you are not doing this, why are you importing the model? That might lead to what the problem is.

As far as I know this should work, unless there is something going on with engines. Is the engine lazy loaded?  I think I remember reading that if you are trying to share models from an engine, you should put the models in a separate repo (addon) and then have the engine and the application both require them. Thats something you also might try.

**Comment by mockey-jockey** [comment]
hey thanks, @cah-briangantzler found a solution for this issue. 

used like this added my engine into the blocklist

```
const EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  let app = new EmberApp(defaults, {
    addons: {
      blacklist: [
        'fastboot-app-server'
      ]
    }
  });

  //...
  return app.toTree();
};
```

**Comment by cah-briangantzler** [comment]
I am aware of what that does, but I dont undersrtand how that fixed your problem. There must have been some conflict you were able to find not evident the information I had.

Glad you found your problem though.
