### ISSUE TITLE
Importing from addon-test-support dir in config throws issue in development env, even when Mirage is disabled.

### ISSUE THREAD

**Issue by andrew-paterson** [miragejs/ember-cli-mirage#2115]
I have recreated the issue here: [https://github.com/andrew-paterson/ember-cli-mirage-boilerplate/pull/new/issue/imports](https://github.com/andrew-paterson/ember-cli-mirage-boilerplate/pull/new/issue/imports).

In `/mirage/config.js` I have an import statement, used to load a static data stub. 

`import mockResponse from  'test-addon-2/test-support/mock-data';`

In `config/environment.js`, I have disabled Mirage as follows:

```
  if (environment === 'development') {
    // ENV.APP.LOG_RESOLVER = true;
    // ENV.APP.LOG_ACTIVE_GENERATION = true;
    // ENV.APP.LOG_TRANSITIONS = true;
    // ENV.APP.LOG_TRANSITIONS_INTERNAL = true;
    // ENV.APP.LOG_VIEW_LOOKUPS = true;
    ENV['ember-cli-mirage'] = {
      enabled: false
    };
  }
```

When I try and load the app in the development environment (Just with `ember serve`) I get the following error:

Uncaught Error: Could not find module `test-addon-2/test-support/mock-data` imported from `ember-cli-mirage-boilerplate/mirage/config

The error does not happen in the tests environment, which makes sense as the imported file is in the `addon-test-support` directory. My question is, why is `mirage/config.js` being processed at all when mirage is disabled?

In my real app, I'm doing this to stub extremely large responses with tonnes of relationships and includes. I know that I could import the static response into my test, and then add it to the db using `server.create`, but performance-wise this takes ages, as I end up having to add each included record in a separate `server.create` operation. Simply importing the data into my route handler, and returning it as it is does much better. Is there another way altogether of stubbing a large complex data set in one operation?

**Comment by cah-briangantzler** [comment]
The files are still being included in the build, so they are still being evaluated. Disabling mirage means it will not start the server, but since the code is still included, it have to be evaluated and so is missing the import.

What you want to do is set https://www.ember-cli-mirage.com/docs/advanced/environment-options#excludefilesfrombuild to false for development. I think that will solve your problem.

**Comment by cah-briangantzler** [comment]
Oh as a side note. If in your test-addon-2 you also have a mirage folder (presumably for that addon's tests) I can show you have to merge that addons mirage folder with the apps mirage folder, then instead of importing tests data from test-support you can import it from the mirage folder (which also will solve your problem since those files are still included in development (unless you exclude them as above)).    If you are interested

**Comment by andrew-paterson** [comment]
Thank you. It would be great to see how to merge with the addon mirage folder, as I like to run tests in the browser by visiting `/tests`.

**Comment by cah-briangantzler** [comment]
note that the mirage folder in the addon should be at tests/dummy/mirage because dummy is the app that runs with ember serve and also the config that tests use. Theres a way to change where that folder is, but it just makes things easier if you put them where they are expected. 

create a file in the root of your addon project, I called it exportMirage.js containing the following
```js

'use strict';

const path = require('path'); // eslint-disable-line
let Funnel = require('broccoli-funnel'); // eslint-disable-line
let MergeTrees = require('broccoli-merge-trees'); // eslint-disable-line

const mirageDefaultDirectory = '/mirage';

let BroccoliDebug;
// let BroccoliDebug = require('broccoli-debug'); // eslint-disable-line

function _shouldIncludeMirageFiles(application, appMirageConfig) {
  if (process.env.EMBER_CLI_FASTBOOT) { // eslint-disable-line
    return false;
  }

  let environment = application.env;
  let enabledInProd = environment === 'production' && appMirageConfig.enabled;
  let explicitExcludeFiles = appMirageConfig.excludeFilesFromBuild;
  if (enabledInProd && explicitExcludeFiles) {
    throw new Error('Mirage was explicitly enabled in production, but its files were excluded '
      + 'from the build. Please, use only ENV[\'ember-cli-mirage\'].enabled in '
      + 'production environment.');
  }
  return enabledInProd || (environment && environment !== 'production' && explicitExcludeFiles !== true);
}

/**
 * Merge the Mirage directory with another tree
 *
 * @param application - the application we are merging into (should be 'this.app' from ember-cli)
 * @param tree - the tree to merge mirage into
 * @param addonMirageDirectory - The directory where mirage is in the addon if not the default directory tests/dummy/mirage
 * @returns {*}
 */
let exportMirage = function exportMirage(application, tree, addonMirageDirectory) { // eslint-disable-line
  let debugTree = BroccoliDebug
    ? BroccoliDebug.buildDebugCallback('exportMirage')
    : function(tree /*, name*/) {
      return tree;
    };

  let appMirageConfig = application.app.project.config(application.app.env)['ember-cli-mirage'] || {};

  let trees = [];

  if (_shouldIncludeMirageFiles(application.app, appMirageConfig)) {//only in dev and test

    let addonMirageDirectoryPath =
      path.join(application.root,
        addonMirageDirectory || path.join("tests", "dummy", mirageDefaultDirectory)
      );

    let mirageTree = new Funnel(addonMirageDirectoryPath, {
      destDir: appMirageConfig.directory || mirageDefaultDirectory,
      allowEmpty: true,
      exclude: ['config.js']
    });

    trees.push(
      debugTree(mirageTree, 'mirageTree')
    );
  }

  trees.push(
    debugTree(tree, 'originalTree')
  );

  let mergedTrees = new MergeTrees(trees, {
    overwrite: true,
    annotation: application.app.modulePrefix
  });

  return debugTree(mergedTrees, 'mergedTrees');
};

module.exports = exportMirage; // eslint-disable-line

```


The in the addon's index.js, do this at the top with the other requires
```
const exportMirage = require('./exportMirage');
```

and then have something like this
```
 treeForApp(appTree) {
    let isDummyApp = this.app.name === 'dummy';
    if (isDummyApp) {
      return appTree;
    } else {
      return exportMirage(this, appTree);
    }
  },
```

As with all merges, if there is a file named the same in both app and addon , app will win. So the mirage/config.js will be overwritten with the app version, what I do is put all my config in the addon in a different file, I create a directory in mirage named the addon then a config.js in there. That way if I merge multiple addons, you know what config comes from where. 


below is my addon tests/dummy/mirage/config,js (using the newer syntax of 2.x so it looks more like MirageJs). You can see I Import my routes from ./ember-rxid-common/config (ember-rxid-common is my addon) and just add it to the routes via `this.config({routes: AddonConfig});`.   Since this file is in the root of the mirage folder, it will be overwritten in the app by the file of the same name. However in the app I just do the same import, define my apps routes and then `this.config({routes: AddonConfig});` and the addons routes will be added as well.
``` js
import { createServer, discoverEmberDataModels, applyEmberDataSerializers } from 'ember-cli-mirage';
import AddonConfig from './ember-rxid-common/config';

export function makeServer(config) {
  let finalConfig = {
    ...config,
    models: { ...discoverEmberDataModels(), ...config.models },
    serializers: applyEmberDataSerializers(config.serializers),
    routes
  };

  return createServer(finalConfig)
}


function routes() {
  this.config({routes: AddonConfig});
}
```

So if you have a mirage model in the addon name the same as the app, the app will overwrite it. If you want to be able to extend your addon's mirage model in the app, then do the same thing addons do with the app directory and put the model in your mirage/addon/models directory and just a re-export in the mirage/models folder.

Thats a lot, hopefully it helps you. I tried putting the exportMirage.js in ember-cli-mirage proper, just so you didnt have to create that file, but for some reason broccoli puts the merged mirage folder at the wrong level. Someone better than I is going to have to figure that out, it should not matter where I require something from, but it seems to. So for the time being each addon has to recreate the file over and over again. sigh.

**Comment by andrew-paterson** [comment]
Thank you, this is a great tip on using centralised Mirage files for multiple apps.
