### ISSUE TITLE
Mirage files are loaded on development environment even when ember-cli-mirage is disabled

### ISSUE THREAD

**Issue by lcoq** [miragejs/ember-cli-mirage#2368]
Version: 2.4.0

Given `ember-cli-mirage` is disabled on development environment : 

```js
// config/environment.js
if (environment === 'development') {
  ENV['ember-cli-mirage'] = {
    enabled: false
  };
}
```

And the Mirage config file : 

```js
// mirage/config.js
import myUtils from "../tests/routes/mirage-routes";
```

The EmberJS development environment is broken, the following error appears on every page : 

> Uncaught Error: Could not find module `myapp/tests/utils/routes/get-entries` imported from `myapp/mirage/config`
>     at missingModule (loader.js:247:1)
>     at findModule (loader.js:258:1)
>     at Module.findDeps (loader.js:168:1)
>     at findModule (loader.js:262:1)
>     at Module.findDeps (loader.js:168:1)
>     at findModule (loader.js:262:1)
>     at requireModule (loader.js:24:1)
>     at r (loader.js:176:1)
>     at resolveInitializer (index.js:10:1)
>     at registerInitializers (index.js:31:1)

This is probably because Ember does not load `tests/` directory in `development` environmment.
I believe `ember-cli-mirage` should do the same with its directory when `ember-cli-mirage` is disabled.

I discovered this because I want to share route handlers functions between `mirage/config.js` file and my tests ( see https://github.com/miragejs/miragejs/issues/1022 ) like this : 

```js
// mirage/config.js
import getPosts from "../tests/utils/routes/get-posts.js"
function routes() {
  this.get("/posts", getPosts);
}
```

```js
// tests/acceptance/application-test.js
import getPosts from "../utils/routes/get-posts.js"
// ...
test("shows current post title", function() {
  // ...
  this.server.get("/posts", function (schema, request) {
    if (request.queryParams["filter[current]"] === "1") {
      return post;
    } else {
      return getPosts(schema, request);
    }
  });
});
```

It indeed works in test environment but completely breaks the development environment.

Am I missing something ?

Thanks !

**Comment by cah-briangantzler** [comment]
Given that `getPosts` accepts schema and request, I would say that is very much a mirage concern and suggest that you move the util from the `tests` directory and put a util in the `mirage` directory. I think would that would solve the problem.

Now for some questions. If you have mirage disabled in dev. Do you want that ALL the time. Is so, I would use this environment variable https://www.ember-cli-mirage.com/docs/advanced/environment-options#excludefilesfrombuild instead of `enabled`. Think that would also solve your problem because then even `config.js` would not be included in you dev build.  (although I do not know how this is going to look in an embroider world)

Given that you defined the route in the mirage config, is that a default, and in the test you are overriding that definition for that one specific for the test? If that route is used ONLY in that test, the you do not really need to define it in the routes if you are going to dynamically add it in the test.

**Comment by lcoq** [comment]
Hi !

> Given that getPosts accepts schema and request, I would say that is very much a mirage concern and suggest that you move the util from the tests directory and put a util in the mirage directory. I think would that would solve the problem.

No sure why it didn't work when I tried it, but it indeed works now :+1: 

> Now for some questions. If you have mirage disabled in dev. Do you want that ALL the time. If so, I would use this environment variable https://www.ember-cli-mirage.com/docs/advanced/environment-options#excludefilesfrombuild instead of enabled. Think that would also solve your problem because then even config.js would not be included in you dev build. (although I do not know how this is going to look in an embroider world)

This is indeed what I was looking for because I never use mirage in dev env, and it works, thank you !

> Given that you defined the route in the mirage config, is that a default, and in the test you are overriding that definition for that one specific for the test? If that route is used ONLY in that test, the you do not really need to define it in the routes if you are going to dynamically add it in the test.

Yes, I have some default route handlers defined in `mirage/config.js` which is used by the majority of my tests, but for some cases, I override those handlers in specific tests. So yep, I need to define route handlers in the mirage config file too.

Thank you very much for your detailed answer, I can close this issue then :slightly_smiling_face:
