### ISSUE TITLE
Application Serializer doesn't work for non-ORM responses

### ISSUE THREAD

**Issue by jasalguero** [miragejs/ember-cli-mirage#892]
Just updated from 0.1 to 0.2.x

Trying to use the default serializer globally (see [my other issue](https://github.com/samselikoff/ember-cli-mirage/issues/891) but mirage is not using it at all, not sure if due to the fact that I have no models (only factories and fixtures)

Is there any way to hook all outgoing responses from Mirage?

**Comment by samselikoff** [comment]
Without models the serializer really just becomes a filtering-type function that runs for all your handlers, which you could do manually in a few ways using just functions. But no, currently the serializer layer is bypassed if the response is not a Mirage/Model or Mirage/Collection.

I'd be happy to help you through fixing this, though. I think it'd be reasonable if all responses went through ApplicationSerializer, even if the default for non-orm responses was a noop.

**Comment by jasalguero** [comment]
thank you for your support @samselikoff, any ideas on how to make that happen?

**Comment by aquamme** [comment]
Data point: For my current pattern of use, it's important that I'm able to bypass the serializer and return a plain response from a route handler.

**Comment by samselikoff** [comment]
I will put this issue on the backlog but it needs to be prioritized. For now I would suggest writing a general function to handle any outgoing logic you want applied to all routes, something like this:

```js
// mirage/utils/handle-request.js
export default function(f) {
  return (schema, request) => {
    let response = f(schema, request);
    
    // final munging
    response.meta = {};
    
    return f;
  };
}

// mirage/config.js
import handleRequest from './utils/handle-request';

export default function() {

  this.get('/users', handleRequest((schema, request) => {
    let json = {};

    return json;
  });

}
```

**Comment by jasalguero** [comment]
hey Sam, that could definitely work in the meantime. But I moved back to the 0.1 in my project since I didn't see any straightforward solution. I'd rather wait for a final solution for this ticket :)

**Comment by samselikoff** [comment]
_**Help wanted: anyone can take this**_: Let's make every response go through the Application serializer, and by default pass through POJOs and POJAs.

Currently all responses go through the `SerializerRegistry` but only models and collections get passed off to the actual serializers. The change we need to make is [right here](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/serializer-registry.js#L43). I would say, move the second `if/else` check for the special case of the array to the beginning of the conditional, and then let all other responses go through `serializer.serialize`.

The serializer then might run into snags, because right now it expects to be dealing with a Model or Collection. I think the only change we'll need to make is in the `serialize` method on the BaseSerializer [here](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/serializer.js#L38). Try checking if it's a Model or Collection (using `this.isModelOrCollection`), and if so, let it go through `buildPayload`; otherwise, just return it.

That way non-orm responses will all go through `ApplicationSerializer`, giving users a centralized extension point to transform parts of their payload.

**Comment by samselikoff** [comment]
Closing this as stale for now.

**Comment by EndangeredMassa** [comment]
I don't see the change from numbers to strings for ids in the upgrade guide. Can that be added even if there is no great way to revert that behavior?

**Comment by samselikoff** [comment]
@EndangeredMassa hey man – sorry to keep dropping the ball on this!

Could you help remind me where this should be added?

**Comment by EndangeredMassa** [comment]
@samselikoff there should probably be a note in the 0.1 -> 0.2 upgrade guide:
https://www.ember-cli-mirage.com/docs/getting-started/upgrade-guide#0-1-x-0-2-upgrade-guide
